apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-policy-v1.0
  labels:
    app: insurance-policy
    version: "1.0"
    environment: development
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: insurance-policy
      version: "1.0"
      environment: development
  template:
    metadata:
      labels:
        app: insurance-policy
        version: "1.0"
        environment: development
    spec:
      containers:
        - name: "insurance-policy-container"
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: MONGO_PORT
            - name: API_CORE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: API_CORE_ENDPOINT
            - name: spring.profiles.active
              value: "development" 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
