apiVersion: v1
kind: Service
metadata:
  name: insurance-policy
  namespace: insurance-development
  labels:
    app: insurance-policy
    version: "1.0"
    environment: development
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: insurance-policy
    version: "1.0"
    environment: development
